CREATE TABLE Users (
    Id INT(8) AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    FKStatus INT(8) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO Users (Username, Password, FKStatus) 
VALUES ('admingeneral', '$2a$08$IIirkJmhyTbQNy2egbLFde.qTYJdR5H2k2smaTY3Q7Scwv4286il2', 1);

CREATE TABLE Statuses (
    Id INT(8) PRIMARY KEY,
    Acronym VARCHAR(100) NOT NULL,
    Description VARCHAR(200) DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Tasks (
    Id INT(8) AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description VARCHAR(255) NOT NULL,
    FKUser INT(8) NOT NULL,
    FKStatus INT(8) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);